name: Build & Publish Release APK

on:
  push:
    branches:
      - main
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Demo APK
        run: ./gradlew assembleDebug

      - name: Upload APK to Github Actions
        if: always()
        uses: actions/upload-artifact@v3
        with:
           name: final-output.apk
           path: |
              app/build/outputs/apk/debug/app-debug.apk

      - name: Releasing using Hub
        uses: kyze8439690/action-release-releaseapk@master
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            APP_FOLDER: app/build/outputs/apk/debug/app-debug.apk
            RELEASE_TITLE: New Build