name: Build & Publish Release APK

on:
  push:
    branches:
      - main
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Release APK
        run: ./gradlew assembleRelease
      - name: Releasing using Hub
        uses: VladDaniliuk/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VERSION_VARIABLE: v0.0.1
          APP_FILE: buildSrc/Android.kt
          APP_FOLDER: ./app/release/app.apk
          CHANGELOG_FILE: ./CHANGELOG.md
          RELEASE_TITLE: New Build
          NAME_VARIABLE: app-release.apk