name: Build & Publish Release APK

on:
  push:
    branches:
      - main
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Generate AAR and APK files
        if: always()
        run: ./gradlew assembleDebug

      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: artifacts.zip
           path: |
              app/build/outputs/apk/debug/app-debug.apk
              dog_network/build/outputs/aar